/**************************************************************************************************
This program generates random numbers. At first it uses a homemade algorithm to generate random 
numbers via linear congruence. The other choices are actually using builtin random number generators 
to show the the differnece between the homemade generator and one that has been used for for many
yers.
***************************************************************************************************/ 


#include <stdio.h> 
#include<stdlib.h>
#include<math.h>


#define max 1000000
#define seed 10


int choose; 

int main()
{

	printf("Please choose 1, 2 or 3. 1 for created generator, 2 for built in and 3 for the realtion.\n");
	scanf("%d", &choose);


	if (choose==1)                                               //Homemade random number generator 
	 {
		int i, old, randx, randy;
   
   		FILE *output;		      
   		output = fopen("Rand1.txt","w");
   
  		old = seed;                        

   		for (i=0; i<max; i++)              
   		 {
     		  randx = (57*old+1) % 256;        
      		  randy = (57*randx+1) % 256;      
     		  fprintf (output, "%i\t%i\n", randx, randy);
		  old  = randy;
   		 }
  
		printf("The data was stored in the Rand1 textfile.\n");
   		fclose(output);
	 }

	if (choose==2)						     //Numnbers generated by builtin rand function
	 {                                                           //Used to show the diffence in the random numbers generated
		int i;                                              
		FILE *output;
		output = fopen("Rand2.txt", "w");
		
		for (i=0; i<max; i++)
		 {	
		  int x=rand()%256;
		  int y=rand()%256;
		  fprintf (output, "%i\t%i\n", x, y);
		 }
	
		fclose(output);

	 }


	if (choose==3)                                               //Used to generate random numbers and check saticfaction of relation  
	 {                                                           //that can provided on PDF format if curious
		float j;
		float maxx;
		maxx=100000;
		FILE *output;
		output = fopen("Rand3.txt", "w");
		for (j=100; j<=maxx; j=j+100)
		 {
			float l;		
			float x,m,y;
			float k=7;
			float sum=0;
			
			for(l=1; l<=j; l++)
			 {
			  x=drand48(); 
			  m=pow((x),(k));
			  sum=sum+m;
			 }	
		
		y=sqrt(j)*((sum/j)-(1/(1+k)));
		fprintf(output, "%e %e \n", j,y);
		 }	
		
		fclose(output);
    	 }
return 0;
}
	
